FROM node:18-slim

# Create app directory
WORKDIR /app

# Install app dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Bundle app source
COPY . .

# Set environment variables
ENV NODE_ENV=production

# Start the worker
CMD ["node", "src/worker.js"] 