receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  memory_limiter:
    check_interval: 1s
    limit_mib: 1024
  resourcedetection:
    detectors: [env, system]
  attributes:
    actions:
      - key: environment
        value: "production"
        action: insert

exporters:
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: "ltams"
    send_timestamps: true
    metric_expiration: 180m
    resource_to_telemetry_conversion:
      enabled: true

  loki:
    endpoint: "http://loki:3100/loki/api/v1/push"
    default_labels_enabled:
      exporter: true
      job: true
      instance: true
    labels:
      resource:
        service.name: "service_name"
        service.version: "service_version"
        host.name: "host_name"
      attributes:
        level: "log_level"
        event_id: "event_id"

  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true

  logging:
    loglevel: debug
    sampling_initial: 5
    sampling_thereafter: 200

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [otlp/tempo, logging]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [prometheus, logging]
    
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch, resourcedetection, attributes]
      exporters: [loki, logging]

  telemetry:
    logs:
      level: "debug"
    metrics:
      level: "detailed"
      address: "0.0.0.0:8888" 