server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: ltams_logs
          __path__: /var/log/ltams/*.log

  - job_name: backend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend_logs
          service: ltams_backend
          __path__: /backend/logs/*.log

  - job_name: frontend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend_logs
          service: ltams_frontend
          __path__: /frontend/logs/*.log

  - job_name: auth_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: auth_logs
          service: ltams_auth
          __path__: /var/log/auth.log

  - job_name: browser_console_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: browser_console_logs
          service: ltams_frontend
          __path__: /app/frontend/logs/browser-console.log
    pipeline_stages:
      - match:
          selector: '{job="browser_console_logs"}'
          stages:
            - json:
                expressions:
                  timestamp: timestamp
                  log_level: log_level
                  service: service
                  environment: environment
                  traceId: traceId
                  userId: userId
                  ipAddress: ipAddress
                  host: host
                  message: message
                  context: context
                  error: error
                  business_event: business_event
            - labels:
                log_level:
                service:
                environment:
                traceId:
                userId:
                ipAddress:
                host:
            - timestamp:
                source: timestamp
                format: RFC3339
            - output:
                source: message 