server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: browser_console_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: browser_console_logs
          service: ltams_frontend
          __path__: /app/frontend/logs/browser-console.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            log_level: log_level
            service: service
            environment: environment
            traceId: traceId
            userId: userId
            ipAddress: ipAddress
            host: host
            message: message
            context: context
            error: error
            business_event: business_event
      - labels:
          log_level:
          service:
          environment:
          userId:
      - timestamp:
          source: timestamp
          format: RFC3339
      - output:
          source: message

  - job_name: backend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: backend
          __path__: /app/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            log_level: log_level
            service: service
            environment: environment
            message: message
      - labels:
          log_level:
          service:
          environment:

  - job_name: frontend_logs
    static_configs:
      - targets:
          - localhost
        labels:
          job: frontend
          __path__: /app/frontend/logs/*.log
    pipeline_stages:
      - json:
          expressions:
            log_level: log_level
            service: service
            environment: environment
            message: message
      - labels:
          log_level:
          service:
          environment: 