groups:
  - name: application_alerts
    rules:
      - alert: HighErrorRate
        expr: sum(rate(http_requests_total{status=~"5.."}[5m])) by (service) / sum(rate(http_requests_total[5m])) by (service) > 0.05
        for: 5m
        labels:
          severity: critical
          team: application
        annotations:
          summary: High error rate detected for {{ $labels.service }}
          description: Error rate is above 5% for the last 5 minutes
          runbook_url: https://wiki.example.com/abc

      - alert: SlowAPIResponse
        expr: histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, service)) > 2
        for: 5m
        labels:
          severity: warning
          team: application
        annotations:
          summary: Slow API response time for {{ $labels.service }}
          description: 95th percentile of response time is above 2 seconds
          runbook_url: https://wiki.example.com/runbooks/slow-api-response

  - name: database_alerts
    rules:
      - alert: HighDatabaseConnections
        expr: pg_stat_activity_count > 100
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: High number of database connections
          description: Database connection count is above 100
          runbook_url: https://wiki.example.com/runbooks/high-db-connections2

      - alert: SlowQueries
        expr: rate(pg_stat_activity_max_tx_duration{datname!=""}[5m]) > 30
        for: 5m
        labels:
          severity: warning
          team: database
        annotations:
          summary: Slow queries detected
          description: Queries taking longer than 30 seconds detected
          runbook_url: https://wiki.example.com/runbooks/slow-queries

  - name: infrastructure_alerts
    rules:
      - alert: HighCPUUsage
        expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: High CPU usage on {{ $labels.instance }}
          description: CPU usage is above 80%
          runbook_url: https://wiki.example.com/runbooks/high-cpu-usage

      - alert: HighMemoryUsage
        expr: (node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes) / node_memory_MemTotal_bytes * 100 > 85
        for: 5m
        labels:
          severity: warning
          team: devops
        annotations:
          summary: High memory usage on {{ $labels.instance }}
          description: Memory usage is above 85%
          runbook_url: https://wiki.example.com/runbooks/high-memory-usage

  - name: business_alerts
    rules:
      - alert: LowConversionRate
        expr: rate(user_registration_success_total[1h]) / rate(user_registration_attempts_total[1h]) < 0.3
        for: 15m
        labels:
          severity: warning
          team: business
        annotations:
          summary: Low user registration conversion rate
          description: User registration conversion rate is below 30%
          runbook_url: https://wiki.example.com/runbooks/low-conversion-rate

      - alert: HighSubscriptionChurn
        expr: rate(subscription_cancellations_total[24h]) / rate(active_subscriptions_total[24h]) > 0.1
        for: 1h
        labels:
          severity: warning
          team: business
        annotations:
          summary: High subscription churn rate
          description: Daily subscription churn rate is above 10%
          runbook_url: https://wiki.example.com/runbooks/high-churn-rate 