global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'ltams-monitor'

rule_files:
  - "rules/database_metrics.yml"
  - "rules/application_metrics.yml"
  - "rules/infrastructure_metrics.yml"
  - "rules/business_metrics.yml"
  - "rules/alerts.yml"
  - "rules/service_dependencies.yml"
  - "rules/rate_limits.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alertmanager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_service_name]
        target_label: service

  - job_name: 'backend'
    static_configs:
      - targets: ['backend:3000']
    metrics_path: '/metrics'

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'node-worker'
    static_configs:
      - targets: ['node-worker:3000']
    metrics_path: '/metrics'

  - job_name: 'python-worker'
    static_configs:
      - targets: ['python-worker:8000']
    metrics_path: '/metrics'

  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:4200']
    metrics_path: '/metrics'

  - job_name: 'mock-api-server'
    static_configs:
      - targets: ['host.docker.internal:3000']
    metrics_path: '/metrics'
    scrape_interval: 5s

  - job_name: 'mysql'
    static_configs:
      - targets: ['mysql-exporter:9104']
    metrics_path: '/metrics'
    scrape_interval: 5s
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
      - source_labels: [__meta_service_name]
        target_label: service 