apiVersion: 1

notifiers:
  - name: Telegram Alerts
    type: telegram
    uid: telegram_alerts
    settings:
      bottoken: ${TELEGRAM_BOT_TOKEN}
      chatid: ${TELEGRAM_CHAT_ID}
      message: |
        🚨 Alert: {{ .Title }}
        Description: {{ .Message }}
        Client ID: {{ .Labels.client_id }}
        Endpoint: {{ .Labels.endpoint }}
        Current Rate: {{ .Value }} requests/minute
        Time: {{ .StartsAt }} 